sudo: required

env:
  - VERSION=3.1.0 TAG=latest
  - VERSION=3.0.1 TAG=3.0.1
  - VERSION=3.1.0 TAG=3.1.0

services:
   - docker

script:
   - ./build.sh -t $TAG -v $VERSION

before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: ./build.sh deploy
     on:
        all_branches: true
