sudo: required

env:
  - VERSION=ozone URL=https://ci.anzix.net/job/hadoop-ozone/lastSuccessfulBuild/artifact/hadoop-dist/target/hadoop-3.1.0-SNAPSHOT.tar.gz

services:
   - docker

script:
   - make build

before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: make deploy
