sudo: required

env:
  - VERSION=latest
  - VERSION=2.9.0 URL=https://archive.apache.org/dist/hadoop/core/hadoop-2.9.0/hadoop-2.9.0.tar.gz
  - VERSION=2.8.2 URL=https://archive.apache.org/dist/hadoop/core/hadoop-2.8.2/hadoop-2.8.2.tar.gz
  - VERSION=2.7.4 URL=https://archive.apache.org/dist/hadoop/core/hadoop-2.7.4/hadoop-2.7.4.tar.gz

services:
   - docker

script:
   - make build

before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: make deploy
     on:
        all_branches: true
